### ISSUE TITLE
rancher rke2 cluster cloud-init param is only single line

### ISSUE THREAD

**Issue by med-jordan** [nutanix/rancher-ui-driver#13]
Please change cloud-init parameter in rke2 template to multiline textbox.
With single line textbox it is not possible to add a cloud-init configuration.

Thanks and BR
Andre

**Comment by tuxtof** [comment]
This UI driver is only used for RKE1 and this is already a multi line textbox

![image](https://github.com/nutanix/rancher-ui-driver/assets/180613/16bd76c9-7921-4ad3-ac99-aee7e4bb3a53)

A Nutanix UI extension is work in progress for RKE2 and will be released soon.
You can contact your Nutanix field team to test it as tech preview

**Comment by med-jordan** [comment]
Hi Christophe,

many thanks for very fast support :)
Happy to hear that a rke2 release is coming soon.

i will contact the field team - in the meantime i used the workaround by adding linebreaks manually in the textbox and that works for now.

Thanks and BR
Andre

**Comment by tuxtof** [comment]
yes adding linebreaks in the RKE2 single line works
i fix it with node driver [v3.4.0](https://github.com/nutanix/docker-machine/releases/tag/v3.4.0)
